// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDny5p8kQ4iHZrJ4esHak698yObj8XUKQI',
    appId: '1:62009849420:web:5211d5b366d9336c65a6e9',
    messagingSenderId: '62009849420',
    projectId: 'flutter-firebase-app-e224b',
    authDomain: 'flutter-firebase-app-e224b.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-e224b.firebasestorage.app',
    measurementId: 'G-1W08BFJB4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8t8g1pWyPsWLmYaIKenlTydT67YSWMKI',
    appId: '1:62009849420:android:41f780212b8630f165a6e9',
    messagingSenderId: '62009849420',
    projectId: 'flutter-firebase-app-e224b',
    storageBucket: 'flutter-firebase-app-e224b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCroDr0B0Z3_YYGSc37WstgBWWv_ozrFxM',
    appId: '1:62009849420:ios:1187ef16d2c1e3f765a6e9',
    messagingSenderId: '62009849420',
    projectId: 'flutter-firebase-app-e224b',
    storageBucket: 'flutter-firebase-app-e224b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCroDr0B0Z3_YYGSc37WstgBWWv_ozrFxM',
    appId: '1:62009849420:ios:1187ef16d2c1e3f765a6e9',
    messagingSenderId: '62009849420',
    projectId: 'flutter-firebase-app-e224b',
    storageBucket: 'flutter-firebase-app-e224b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDny5p8kQ4iHZrJ4esHak698yObj8XUKQI',
    appId: '1:62009849420:web:9ec66c4c7123d97c65a6e9',
    messagingSenderId: '62009849420',
    projectId: 'flutter-firebase-app-e224b',
    authDomain: 'flutter-firebase-app-e224b.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-e224b.firebasestorage.app',
    measurementId: 'G-KLRQVD3MEF',
  );
}
